### ISSUE TITLE
Verified als Parameter in der Suche und in den Objekten

### ISSUE THREAD

**Issue by TimGuenther** [binary-butterfly/shared-delivery#13]
Meine Beta Testerin Zuhause hat bemerkt das es schön wäre nur die schon verifizierten Läden angezeigt zu bekommen und nicht alle aus dem Importierten OSM Daten. Das sollte auch die Karten schneller machen.

**Comment by TimGuenther** [comment]
Im GeoJSON fänd ich es am wichtigsten

**Comment by the-infinity** [comment]
Done. Parameter für die Suche ist revisit-required:
- Parameter existiert nicht bedeutet Filter nicht gesetzt
- revisit-required = 1 bedeutet "hat noch keine Aktualiserung"
- revisit-required = 0 bedeutet "hat aktualisierung
