### ISSUE TITLE
Daten erneuern nach Verifizierung

### ISSUE THREAD

**Issue by TimGuenther** [binary-butterfly/shared-delivery#26]
Aktuell kann man keine neuen Daten eingeben wenn ein Shop schon aktualisiert hat.
https://lokalwirkt.de/store/29939

Sollten wir das nicht trotzdem als dialog ausgeben?

**Comment by TimGuenther** [comment]
Vergleich https://lokalwirkt.de/store/5960, vllt. nicht ganz so prominent aber es sollte ja trotzdem so sein falls sich was ändert.

**Comment by the-infinity** [comment]
Resolved in https://github.com/binary-butterfly/shared-delivery/commit/dfde1fcbdb4ea7c5c215bc30a87835e1cc679e60 .
