### ISSUE TITLE
Weitere Geschäfte

### ISSUE THREAD

**Issue by Matthias84** [binary-butterfly/shared-delivery#31]
Bei Bastelbedarf / DIY vermisse ich Stoffhändler (shop=fabric / shop=sewing)

**Comment by the-infinity** [comment]
Ist beides seit ein paar Tagen drin: . Heute Abend starte ich noch mal einen Massenimport, damit die Updates auch in der Übersicht ankommen. 

Siehe https://github.com/binary-butterfly/shared-delivery/blob/master/webapp/common/constants.py#L101
