### ISSUE TITLE
Funktion Ich kenne die aktuellen Öffnungszeiten

### ISSUE THREAD

**Issue by OpenDataBonn** [binary-butterfly/shared-delivery#38]
Sobald einmal die andere Öffnungszeiten als Vorschlag eingegeben sind, ist die Funktion nicht mehr anwählbar. Da sich im zeitlichen Verlauf aber weitere Änderungen ergeben können, wäre eine dauerhafte Möglichkeit ohne Login Änderungsvorschläge einzubringen hilfreich.

**Comment by the-infinity** [comment]
Erledigt.
