### ISSUE TITLE
Ansicht Backend Freigabeseite bei Änderungsvorschlägen

### ISSUE THREAD

**Issue by OpenDataBonn** [binary-butterfly/shared-delivery#40]
Bei der Freigabe von Änderungen im Backend erscheinen nur die Öffnungszeiten und nicht alle anderen Einträge, zu denen es Änderungsvorschläge gibt. Also z.B. Telefon, Webseite, Adresse, Lieferdienst ...

**Comment by the-infinity** [comment]
Bäh, der Bug war doof. Habe aus Versehen immer direkt abgespeichert abseits der Öffnungszeiten.
