### ISSUE TITLE
Änderungsformular: nach Submit + Fehlermeldung sind Öffnungszeiten weg

### ISSUE THREAD

**Issue by kadevau** [binary-butterfly/shared-delivery#41]
Wenn man das Änderungsformular abschickt, mit neuen/geänderten Öffnungszeiten (hier: Abholung), und bekommt eine Fehlermeldung wg. z.B. fehlender Adresse, sind die eingetragenen Öffnungszeiten weg.

**Comment by the-infinity** [comment]
Duplikat von #36 .
