### ISSUE TITLE
Bug: Backend auf der Seite Verbesserungsvorschläge 

### ISSUE THREAD

**Issue by OpenDataBonn** [binary-butterfly/shared-delivery#49]
Im Backend auf der Seite Verbesserungsvorschläge kann unter i Aktionen dann keine Vorschläge gelöscht werden. Funktion zeigt zwar an, dass gelöscht wurde, der Eintrag ist aber weiterhin in der Liste. Beispiel Bonn: Eintrag 7.4, 12:44 | Kugelfisch Sushi · Bar

Zweiter Bug: Gleiche Seite und Aktionen ist bei der Funktion Einzeln bearbeiten: Die Bearbeitung springt auf einen ganz anderen Datensatz. 

Dritter Bug: Unter Verbesserungsvorschläge löschen führt dazu, dass das Geschäft komplett gelöscht wird und nicht nur der Verbesserungsvorschlag.

**Comment by lyzzy** [comment]
Beispiel für Fall 1: https://lokalwirkt.de/admin/store/suggestion/10759/show
