### ISSUE TITLE
Vorschlag: Linkeintrag Gutscheinshop hinzufügen

### ISSUE THREAD

**Issue by OpenDataBonn** [binary-butterfly/shared-delivery#52]
Zusätzlich zum Onlineshop wäre zusätzlich ein Eintrag zu einem Online-Guscheinshop hilfreich. Das können ja zwei unterschiedliche Plattformen sein. 

Kartenansicht vllt. auch filterbar nach Onlineshop und Gutscheinshop sowie Abholung- und Bringdienste.

**Comment by the-infinity** [comment]
Bitte immer nur eine Sache in einem Issue, sonst kann man die nicht so gut abarbeiten. :)
