### ISSUE TITLE
Neue Kategorien 

### ISSUE THREAD

**Issue by kallipick** [binary-butterfly/shared-delivery#56]
Kategorie Drogerie umbenennen in Drogerie / Reformhaus
Shop = Medical_supply Sanitätshaus / Orthopädietechnik
health_specialty = naturopath Heilpraktiker
Shop = agrarian Landwirtschaftliche Produkte
Shop = print Druckerei

**Comment by the-infinity** [comment]
> Kategorie Drogerie umbenennen in Drogerie / Reformhaus

Reformhaus wird bei OSM unter 

> Shop = Medical_supply Sanitätshaus / Orthopädietechnik

Das ist schon drin. Ich lass mal n Reimport von allem laufen.

> health_specialty = naturopath Heilpraktiker

Das wird bei OSM unter health=alternative = Alternativmedizin zusammengefasst. health_specialty ist dann eine Unterkategorisierung, das kann lokalwirkt (noch) nicht. Alternative Medizin hab ich nu hinzugefügt.

> Shop = agrarian Landwirtschaftliche Produkte

Das ist auch bereits drin. Kommt auch mit dem Reimport mit rein.

Shop = print Druckerei

Das gibt es in OSM so nicht. Wohl aber gibt es craft=printer, das habe ich nun hinzugefügt.
