### ISSUE TITLE
Neue Kategorien

### ISSUE THREAD

**Issue by kallipick** [binary-butterfly/shared-delivery#66]
tourism=campe_site  Campingplatz
Amenity=dance_school Tanzschule
sport=yoga Yogastudio
craft=caterer Catering

**Comment by kallipick** [comment]
Kategorie Rechtsanwalt, Notar
office=lawyer

**Comment by lyzzy** [comment]
Es fehlt auch noch was für Sportstudio/Fitnessstudio (ich weiß nicht, welche Notation hier verwendet wird, daher nur als Hinweis)

**Comment by kallipick** [comment]
sport=Fitness Fitnessstudio, Sportstudio, Gym

Bitte noch Kategorie Pysiotherapie in Physiotherapie umbennen.

**Comment by lyzzy** [comment]
Kunsthandwerk
