### ISSUE TITLE
Wort fehlt

### ISSUE THREAD

**Issue by lyzzy** [binary-butterfly/shared-delivery#68]
... auf https://lokalwirkt.de/store-map
“Es werden nur Geschäfte mit aktualisierten Öffnungszeiten angezeigt. Wenn Sie die Öffnungszeiten eines weiteren Geschäftes ............(hier fehlt ein Verb), freuen wir uns über die Eingabe in unserer Suche.”

Vorschlag: Hier werden nur Geschäfte mit aktualisierten Öffnungszeiten angezeigt. Wenn Sie die Informationen eines anderen Geschäfts anpassen möchten, nutzen Sie bitte die Suche.

**Comment by the-infinity** [comment]
Merged.
