### ISSUE TITLE
Musteranschreiben Mitmachen

### ISSUE THREAD

**Issue by kallipick** [binary-butterfly/shared-delivery#70]
Das Musteranschreiben zum Mitmachen müsste auf die aktuelle Lage und auf die Wirkung von lokalwirkt nach der Pandemiezeit angepasst werden.

Dies kann direkt im Code erfolgen:
https://github.com/binary-butterfly/shared-delivery/blob/master/webapp/frontend/templates/mitmachen.html

**Comment by lyzzy** [comment]
Das übernehme ich gerne, habe aber keine Schreibrechte. Wär' das ok, mir das Recht zu geben? Sonst schmeiße ich morgen oder übermorgen einen Entwurf als plaintext hier rein und jemand anderes muss es einfügen.
