### ISSUE TITLE
Fehler bei Speicherung der Geschäftsdaten

### ISSUE THREAD

**Issue by kallipick** [binary-butterfly/shared-delivery#72]
Meldung von Askan am 21.04.
Eine Sache würde mir bei der Datenpflege helfen: Bei einer falschen Angabe (zB Telefonnummer hat nicht die richtigen Zeichen) und dem anschließenden abspeichern der Daten, gehen die Öffnungszeiten flöten. Das kostet Zeit, Könnten die zufällig erhalten bleiben?

**Comment by lyzzy** [comment]
Hatt ich schon gemeldet :-) siehe #58

ich schließe das dann hier
