### ISSUE TITLE
Bitte Suchoption Region=keine einrichten

### ISSUE THREAD

**Issue by lyzzy** [binary-butterfly/shared-delivery#76]
Issue #75 führt dann bei Ungeduldigen auch dazu, dass eine Firma 4mal angelegt wird ... 
Kann bitte kurzfristig die Möglichkeit eingerichtet werden, nach Datensätzen zu suchen, bei denen das Feld Region nicht gefüllt ist? dann können die mit einem Rutsch korrigiert werden.

**Comment by the-infinity** [comment]
Done.
